import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getLatestQualityReport } from '@/lib/services/gap.service';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json().catch(() => ({}));
        const detectionType = body.type || 'content'; // 'content' or 'people'

        console.log(`Fetching latest ${detectionType} quality report...`);

        // Fetch the latest report from the database (generated by GitHub Actions)
        const report = await getLatestQualityReport(detectionType === 'people' ? 'people' : 'content');

        if (!report) {
            return NextResponse.json({
                success: true,
                summary: {
                    metadata: 0,
                    total: 0,
                },
                stored: 0,
                message: 'No quality report found. Please run the GitHub Actions workflow first.',
                report: null
            });
        }

        return NextResponse.json({
            success: true,
            summary: {
                metadata: report.total_issues,
                total: report.total_issues,
                checked: report.total_checked,
                complete: report.total_complete
            },
            stored: 0, // No longer storing gaps individually in gap_registry
            message: `Found ${report.total_issues} issues from latest report (${new Date(report.created_at).toLocaleDateString()})`,
            report: report
        });

    } catch (error) {
        console.error('Gap report fetch error:', error);
        return NextResponse.json(
            { error: 'Failed to fetch gap report', details: String(error) },
            { status: 500 }
        );
    }
}
