-- Create quality_reports table for storing validation results
CREATE TABLE IF NOT EXISTS quality_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_type TEXT NOT NULL CHECK (report_type IN ('content', 'people', 'full')),
    total_checked INT NOT NULL,
    total_complete INT NOT NULL,
    total_issues INT NOT NULL,
    issues_by_field JSONB NOT NULL DEFAULT '{}'::jsonb,
    priority_items JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for efficient querying
CREATE INDEX IF NOT EXISTS idx_quality_reports_type_date ON quality_reports(report_type, created_at DESC);

-- Add comment
COMMENT ON TABLE quality_reports IS 'Stores data quality validation reports generated by GitHub Actions scripts';
COMMENT ON COLUMN quality_reports.report_type IS 'Type of report: content, people, or full';
COMMENT ON COLUMN quality_reports.issues_by_field IS 'JSON object with field names as keys and issue counts as values';
COMMENT ON COLUMN quality_reports.priority_items IS 'JSON array of top items needing enrichment';
