import { useState, useEffect } from 'react';
import { Calendar, TrendingUp, TrendingDown, RefreshCw } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

interface QualityReport {
    id: string;
    report_type: 'content' | 'people';
    total_checked: number;
    total_complete: number;
    total_issues: number;
    issues_by_field: Record<string, number>;
    created_at: string;
}

export default function QualityReportsTable() {
    const [reports, setReports] = useState<QualityReport[]>([]);
    const [loading, setLoading] = useState(true);
    const [activeFilter, setActiveFilter] = useState<'all' | 'content' | 'people'>('all');

    const fetchReports = async () => {
        setLoading(true);
        try {
            let query = supabase
                .from('quality_reports')
                .select('*')
                .order('created_at', { ascending: false })
                .limit(50);

            if (activeFilter !== 'all') {
                query = query.eq('report_type', activeFilter);
            }

            const { data, error } = await query;

            if (error) throw error;
            setReports(data || []);
        } catch (error) {
            console.error('Failed to fetch quality reports:', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchReports();
    }, [activeFilter]);

    const getCompletionRate = (report: QualityReport) => {
        return Math.round((report.total_complete / report.total_checked) * 100);
    };

    const getTopIssues = (issuesByField: Record<string, number>) => {
        return Object.entries(issuesByField)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 3)
            .map(([field, count]) => `${field} (${count})`);
    };

    return (
        <div className="bg-zinc-900/50 backdrop-blur-sm border border-zinc-800 rounded-xl p-6">
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h2 className="text-2xl font-bold text-white mb-1">Quality Reports</h2>
                    <p className="text-sm text-zinc-400">Historical quality validation reports from GitHub Actions</p>
                </div>
                <button
                    onClick={fetchReports}
                    className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-medium transition-colors flex items-center gap-2"
                >
                    <RefreshCw className="w-4 h-4" />
                    Refresh
                </button>
            </div>

            {/* Filters */}
            <div className="flex gap-3 mb-6">
                {['all', 'content', 'people'].map((filter) => (
                    <button
                        key={filter}
                        onClick={() => setActiveFilter(filter as any)}
                        className={`px-4 py-2 rounded-lg font-medium transition-colors ${activeFilter === filter
                            ? 'bg-purple-600 text-white'
                            : 'bg-zinc-800 text-zinc-400 hover:bg-zinc-700'
                            }`}
                    >
                        {filter.charAt(0).toUpperCase() + filter.slice(1)}
                    </button>
                ))}
            </div>

            {/* Reports Table */}
            {loading ? (
                <div className="text-center py-12">
                    <div className="animate-spin w-8 h-8 border-2 border-purple-500 border-t-transparent rounded-full mx-auto mb-3"></div>
                    <p className="text-sm text-zinc-400">Loading reports...</p>
                </div>
            ) : reports.length === 0 ? (
                <div className="text-center py-12 text-zinc-500">
                    <Calendar className="w-12 h-12 mx-auto mb-3 opacity-50" />
                    <p className="text-sm">No quality reports found</p>
                    <p className="text-xs mt-2">Reports are generated by scheduled GitHub Actions workflows</p>
                </div>
            ) : (
                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead>
                            <tr className="border-b border-zinc-700">
                                <th className="text-left text-sm font-medium text-zinc-400 pb-3">Date</th>
                                <th className="text-left text-sm font-medium text-zinc-400 pb-3">Type</th>
                                <th className="text-right text-sm font-medium text-zinc-400 pb-3">Total</th>
                                <th className="text-right text-sm font-medium text-zinc-400 pb-3">Complete</th>
                                <th className="text-right text-sm font-medium text-zinc-400 pb-3">Issues</th>
                                <th className="text-right text-sm font-medium text-zinc-400 pb-3">Rate</th>
                                <th className="text-left text-sm font-medium text-zinc-400 pb-3 pl-4">Top Issues</th>
                            </tr>
                        </thead>
                        <tbody>
                            {reports.map((report) => {
                                const completionRate = getCompletionRate(report);
                                const topIssues = getTopIssues(report.issues_by_field);

                                return (
                                    <tr key={report.id} className="border-b border-zinc-800 hover:bg-zinc-800/30">
                                        <td className="py-3 text-sm text-zinc-300">
                                            {new Date(report.created_at).toLocaleString()}
                                        </td>
                                        <td className="py-3">
                                            <span className={`px-2 py-1 rounded text-xs font-medium ${report.report_type === 'content'
                                                ? 'bg-blue-900/20 text-blue-400 border border-blue-500/30'
                                                : 'bg-purple-900/20 text-purple-400 border border-purple-500/30'
                                                }`}>
                                                {report.report_type === 'content' ? '📺 Content' : '👥 People'}
                                            </span>
                                        </td>
                                        <td className="py-3 text-right text-white font-mono">{report.total_checked.toLocaleString()}</td>
                                        <td className="py-3 text-right text-green-400 font-mono">{report.total_complete.toLocaleString()}</td>
                                        <td className="py-3 text-right text-red-400 font-mono">{report.total_issues.toLocaleString()}</td>
                                        <td className="py-3 text-right">
                                            <div className="flex items-center justify-end gap-2">
                                                <div className="w-20 bg-zinc-700 rounded-full h-2">
                                                    <div
                                                        className={`h-full rounded-full ${completionRate >= 80 ? 'bg-green-500' :
                                                            completionRate >= 60 ? 'bg-yellow-500' : 'bg-red-500'
                                                            }`}
                                                        style={{ width: `${completionRate}%` }}
                                                    ></div>
                                                </div>
                                                <span className="text-sm text-zinc-300 w-12 text-right">{completionRate}%</span>
                                            </div>
                                        </td>
                                        <td className="py-3 pl-4 text-xs text-zinc-400 max-w-xs truncate">
                                            {topIssues.join(', ')}
                                        </td>
                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
